
skillMetadata:
  sections:
    - name: Shelly light details
      fields:
        - name: name1
          type: text
          label: Your name for light 1
          value: ""
        - name: ip1
          type: text
          label: IP address (x.x.x.x)
          value: ""
        - name: name2
          type: text
          label: Your name for light 2
          value: ""
        - name: ip2
          type: text
          label: IP address (x.x.x.x)
          value: ""
        - name: name3
          type: text
          label: Your name for light 3
          value: ""
        - name: ip3
          type: text
          label: IP address (x.x.x.x)
          value: ""
        - name: name4
          type: text
          label: Your name for light 4
          value: ""
        - name: ip4
          type: text
          label: IP address (x.x.x.x)
          value: ""
